export let FETCH_SEARCH_MOVIE_REQUEST = "FETCH_SEARCH_MOVIE_REQUEST";
export let FETCH_SEARCH_MOVIE_SUCCESS = "FETCH_SEARCH_MOVIE_SUCCESS";
export let FETCH_SEARCH_MOVIE_FAILURE = "FETCH_SEARCH_MOVIE_FAILURE";
export let CHANGE_SEARCH_TEXT = "CHANGE_SEARCH_SEARCH_TEXT";
export let CHANGE_SEARCH_FINAL_TEXT = "CHANGE_SEARCH_FINAL_TEXT";
