export let FETCH_TOP_RATE_TV_DATA_REQUEST = "FETCH_TOP_RATE_TV_DATA_REQUEST";
export let FETCH_TOP_RATE_TV_DATA_SUCCESS = "FETCH_TOP_RATE_TV_DATA_SUCCESS";
export let FETCH_TOP_RATE_TV_DATA_FAILURE = "FETCH_TOP_RATE_TV_DATA_FAILURE";
export let CHANGE_INFO_SHOW_TV = "CHANGE_INFO_SHOW_TV";
