export let FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export let FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export let FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export let CHANGE_PAGE = "CHANGE_PAGE";
