export let FETCH_WATCHED_LIST_REQUEST = "FETCH_WATCHED_LIST_REQUEST";
export let FETCH_WATCHED_LIST_SUCCESS = "FETCH_WATCHED_LIST_SUCCESS";
export let FETCH_WATCHED_LIST_FAILURE = "FETCH_WATCHED_LIST_FAILURE";
export let ADD_ID_TO_LIST = "ADD_ID_TO_LIST";
export let REMOVE_ID_FROM_LIST = "REMOVE_ID_FROM_LIST";
export let CHANGE_REMOVE_CARD = "CHANGE_REMOVE_CARD";
export let SET_REMOVE_DATA = "SET_REMOVE_DATA";
