export let FETCH_TOP_RATE_DATA_REQUEST = "FETCH_TOP_RATE_DATA_REQUEST";
export let FETCH_TOP_RATE_DATA_SUCCESS = "FETCH_TOP_RATE_DATA_SUCCESS";
export let FETCH_TOP_RATE_DATA_FAILURE = "FETCH_TOP_RATE_DATA_FAILURE";
export let CHANGE_INFO_SHOW = "CHANGE_INFO_SHOW";
